Branch 0.7.10 has been renamed as 0.7

diff --git a/mozilla/xpfe/bootstrap/mozilla.in b/mozilla/xpfe/bootstrap/mozilla.in
--- a/mozilla/xpfe/bootstrap/mozilla.in
+++ b/mozilla/xpfe/bootstrap/mozilla.in
@@ -1,52 +1,32 @@
 #!/bin/sh
 #
-# ***** BEGIN LICENSE BLOCK *****
-# Version: MPL 1.1/GPL 2.0/LGPL 2.1
+# The contents of this file are subject to the Netscape Public License
+# Version 1.0 (the "NPL"); you may not use this file except in
+# compliance with the NPL.  You may obtain a copy of the NPL at
+# http://www.mozilla.org/NPL/
 #
-# The contents of this file are subject to the Mozilla Public License Version
-# 1.1 (the "License"); you may not use this file except in compliance with
-# the License. You may obtain a copy of the License at
-# http://www.mozilla.org/MPL/
-#
-# Software distributed under the License is distributed on an "AS IS" basis,
-# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
+# Software distributed under the NPL is distributed on an "AS IS" basis,
+# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL
 # for the specific language governing rights and limitations under the
-# License.
+# NPL.
 #
-# The Original Code is mozilla.org Code.
+# The Initial Developer of this code under the NPL is Netscape
+# Communications Corporation.  Portions created by Netscape are
+# Copyright (C) 1998 Netscape Communications Corporation.  All Rights
+# Reserved.
 #
-# The Initial Developer of the Original Code is
-# Netscape Communications Corporation.
-# Portions created by the Initial Developer are Copyright (C) 1998
-# the Initial Developer. All Rights Reserved.
-#
-# Contributor(s):
-#
-# Alternatively, the contents of this file may be used under the terms of
-# either of the GNU General Public License Version 2 or later (the "GPL"),
-# or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
-# in which case the provisions of the GPL or the LGPL are applicable instead
-# of those above. If you wish to allow use of your version of this file only
-# under the terms of either the GPL or the LGPL, and not to allow others to
-# use your version of this file under the terms of the MPL, indicate your
-# decision by deleting the provisions above and replace them with the notice
-# and other provisions required by the GPL or the LGPL. If you do not delete
-# the provisions above, a recipient may use your version of this file under
-# the terms of any one of the MPL, the GPL or the LGPL.
-#
-# ***** END LICENSE BLOCK *****
 
-## $Id: mozilla.in,v 1.8.8.8 2008/01/10 18:47:15 reed%reedloden.com Exp $
+## $Id: mozilla.in,v 1.6 2004/02/20 18:13:46 pkw%us.ibm.com Exp $
 ## 
 ## Usage:
 ##
 ## $ mozilla [args]
 ##
-## This script is meant to run the application binary from either 
+## This script is meant to run the mozilla-bin binary from either 
 ## mozilla/xpfe/bootstrap or mozilla/dist/bin.
 ##
 ## The script will setup all the environment voodoo needed to make
-## the application binary to work.
+## the mozilla-bin binary to work.
 ##
 
 moz_pis_startstop_scripts()
@@ -95,164 +75,64 @@ moz_pis_startstop_scripts()
 moz_libdir=%MOZAPPDIR%
 MRE_HOME=%MREDIR%
 
-# Use run-mozilla.sh in the current dir if it exists
-# If not, then start resolving symlinks until we find run-mozilla.sh
-found=0
-progname="$0"
-curdir=`dirname "$progname"`
-run_moz="$curdir/run-mozilla.sh"
-if test -x "$run_moz"; then
-  dist_bin="$curdir"
-  found=1
+# honor MOZILLA_FIVE_HOME if it's there
+if [ -n "$MOZILLA_FIVE_HOME" ] ; then
+  dist_bin="$MOZILLA_FIVE_HOME"
 else
-  here=`/bin/pwd`
-  while [ -h "$progname" ]; do
-    bn=`basename "$progname"`
-    cd `dirname "$progname"`
-    progname=`/bin/ls -l "$bn" | sed -e 's/^.* -> //' `
-    progbase=`basename "$progname"`
-    if [ ! -x "$progname" ]; then
-      break
-    fi
-    curdir=`dirname "$progname"`
-    run_moz="$curdir/run-mozilla.sh"
-    if [ -x "$run_moz" ]; then
-      cd "$curdir"
-      dist_bin=`pwd`
-      run_moz="$dist_bin/run-mozilla.sh"
-      found=1
-      break
-    fi
-  done
-  cd "$here"
-fi
-if [ $found = 0 ]; then
-  # Check default compile-time libdir
-  if [ -x "$moz_libdir/run-mozilla.sh" ]; then
-    dist_bin="$moz_libdir"
-    run_moz="$moz_libdir/run-mozilla.sh"
-  else 
-    echo "Cannot find %MOZ_APP_DISPLAYNAME% runtime directory. Exiting."
-    exit 1
-  fi
-fi
-
-if [ -z "$MOZ_NO_REMOTE" ] && [ $# -lt 5 ]; then
-  mail=0
-  compose=0
-  profile=""
-  extra=""
-  i=1
-  while [ $i -le $# ]; do
-    eval opt=\$$i
-    if [ $mail -eq 1 ] || [ $compose -eq 1 ]; then
-      # look for extra arg for mail/compose
-      # multiply by 2 to prevent us from coming back here
-      mail=`expr $mail \* 2`
-      compose=`expr $compose \* 2`
-      # make sure it's not the next flag
-      if [ `expr "$opt" : '-.*'` -eq 0 ]; then
-        extra=",$opt"
-        i=`expr $i + 1`
-        continue
-      fi
-    fi
-    case "$opt" in
-      -mail)
-        # look for an optional extra arg next pass
-        mail=1
-        ;;
-      -compose)
-        # look for an optional extra arg next pass
-        compose=1
-        ;;
-      -P)
-        # extra arg is required.  look for it now
-        j=`expr $i + 1`
-        eval profile=\$$j
-        # make sure it's not a flag
-        if [ -n "$profile" ] && [ `expr "$profile" : '-.*'` -eq 0 ]; then
-          profile="-p $profile"
-          i=$j
-        else
-          MOZ_NO_REMOTE=1
-          break
-        fi
-        ;;
-      -*)
-        # we don't recognize this flag, so bail
-        MOZ_NO_REMOTE=1
+  # Use run-mozilla.sh in the current dir if it exists
+  # If not, then start resolving symlinks until we find run-mozilla.sh
+  found=0
+  progname=$0
+  curdir=`dirname "$progname"`
+  run_moz="$curdir/run-mozilla.sh"
+  if test -x "$run_moz"; then
+    dist_bin=$curdir
+    found=1
+  else
+    here=`/bin/pwd`
+    while [ -h "$progname" ]; do
+      bn=`basename "$progname"`
+      cd `dirname "$progname"`
+      progname=`/bin/ls -l "$bn" |sed -e 's/^.* -> //' `
+      if [ ! -x "$progname" ]; then
         break
-        ;;
-      *)
-        if [ $i -eq $# ]; then
-          # If this is the last command line argument and it doesn't begin with 
-          # a '-' it's probably a url.
-          URL="$opt"
-        else
-          # URL must be the last argument.  If it isn't, fallback
-          MOZ_NO_REMOTE=1
-          break
-        fi
-        ;;
-    esac
-    i=`expr $i + 1`
-  done
-
-  MOZ_CLIENT_PROGRAM="$dist_bin/mozilla-xremote-client"
-
-  if [ "$OSTYPE" = "beos" ]; then
-    mimeset -F "$MOZ_CLIENT_PROGRAM"
-  fi
-
-  # Open a new tab/window in an existing instance if we can find one.  Don't try if
-  # there are more than 2 arguments, or the second argument is a flag (like -P)
-  appname="%MOZ_APP_NAME%"
-  if [ -z "$MOZ_NO_REMOTE" ] && 
-     "${run_moz}" "$MOZ_CLIENT_PROGRAM" $profile -a "${appname}" 'ping()' 2>/dev/null >/dev/null; then
-
-    if [ $mail -ne 0 ]; then
-      # -mail was given
-      exec "${run_moz}" "$MOZ_CLIENT_PROGRAM" $profile -a "${appname}" "xfeDoCommand(openInbox${extra})"
-    elif [ $compose -ne 0 ]; then
-      # -compose was given
-      exec "${run_moz}" "$MOZ_CLIENT_PROGRAM" $profile -a "${appname}" "xfeDoCommand(composeMessage${extra})"
-    elif [ -z "$URL" ]; then
-      # No command line args. Open new window.
-      exec "${run_moz}" "$MOZ_CLIENT_PROGRAM" $profile -a "${appname}" "xfeDoCommand(openBrowser)"
-    fi
-
-    # There's a URL.  Try to send it to a running instance.
-    if [ `expr "${URL}" : '.*:/.*'` -eq 0 -a \( -f "${URL}" -o -d "${URL}" \) ]; then
-      # The URL seems to be a local file/directory, so prepend "file://"
-      # First, check if it is absolutely specified (ie. /home/foo/file vs. ./file)
-      # If it is just "relatively" (./file) specified, make it absolutely
-      if [ `expr "${URL}" : '/.*'` -eq 0 ]; then
-        URL="`pwd`/${URL}"
       fi
-      URL="file://${URL}"
+      curdir=`dirname "$progname"`
+      run_moz="$curdir/run-mozilla.sh"
+      if [ -x "$run_moz" ]; then
+        cd "$curdir"
+        dist_bin=`pwd`
+        found=1
+        break
+      fi
+    done
+    cd "$here"
+  fi
+  if [ $found = 0 ]; then
+    # Check default compile-time libdir
+    if [ -x "$moz_libdir/run-mozilla.sh" ]; then
+      dist_bin=$moz_libdir
+    else 
+      echo "Cannot find mozilla runtime directory. Exiting."
+      exit 1
     fi
-
-    exec "${run_moz}" "$MOZ_CLIENT_PROGRAM" $profile -a "${appname}" "openURL(${URL})"
   fi
 fi
-
-# Default action - no running instance
 
 script_args=""
+moreargs=""
 debugging=0
 MOZILLA_BIN="%MOZILLA-BIN%"
 
 if [ "$OSTYPE" = "beos" ]; then
-  mimeset -F "$MOZILLA_BIN"
+  mimeset -F $MOZILLA_BIN
 fi
 
-pass_arg_count=0
-while [ $# -gt $pass_arg_count ]
+while [ $# -gt 0 ]
 do
   case "$1" in
-    -p | --pure | -pure)
-      MOZILLA_BIN="${MOZILLA_BIN}.pure"
+    -p | -pure)
+      MOZILLA_BIN="%MOZILLA-BIN%.pure"
       shift
       ;;
     -g | --debug)
@@ -265,16 +145,14 @@ do
       shift 2
       ;;
     *)
-      # Move the unrecognized argument to the end of the list.
-      arg="$1"
-      shift
-      set -- "$@" "$arg"
-      pass_arg_count=`expr $pass_arg_count + 1`
+      moreargs="$moreargs \"$1\""
+      shift 1
       ;;
   esac
 done
 
 export MRE_HOME
+eval "set -- $moreargs"
 
 ## Start addon scripts
 moz_pis_startstop_scripts "start"
